# Generated by Django 5.0.3 on 2024-03-23 15:30

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=6, max_length=6, prefix='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='url',
            name='short',
            field=models.CharField(max_length=6),
        ),
    ]
