# Generated by Django 5.0.3 on 2024-03-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_url_id_alter_url_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
