# Generated by Django 5.0.3 on 2024-03-23 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_alter_url_short'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='short',
        ),
    ]
